name: Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen libspdlog-dev liblua5.4-dev python3-dev cppcheck swig libfltk1.3-dev libgtest-dev
        version: 1.0

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DFUNZEL_ENABLE_OPENCL_BACKEND=OFF -DFUNZEL_USE_INTERNAL_BLAS=ON -DFUNZEL_ENABLE_CPPCHECK=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      uses: sudo-bot/action-kcov@latest
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target kcov
